function originFor(hostname: string, port: number): string {
  const host = hostname.includes(':') ? `[${hostname}]` : hostname;
  return `http://${host}:${port}`;
}

/** Checks whether a URL is permitted to open in a new local Electron window. */
export function isAllowedLocalWindowUrl(rawUrl: string, port: number, localIp?: string): boolean {
  if (rawUrl === 'about:blank' || rawUrl === '') return true;
  try {
    const parsed = new URL(rawUrl);
    if (parsed.protocol !== 'http:' || parsed.username || parsed.password) return false;

    const allowedOrigins = new Set([
      originFor('localhost', port),
      originFor('127.0.0.1', port),
      originFor('::1', port),
      ...(localIp ? [originFor(localIp, port)] : []),
    ]);

    return allowedOrigins.has(parsed.origin);
  } catch {
    return false;
  }
}

export function isSafeExternalUrl(rawUrl: string): boolean {
  try {
    const parsed = new URL(rawUrl);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
}

/** Checks the narrow wa.me URL shape generated by the renderer share flow. */
export function isSafeWhatsAppShareUrl(rawUrl: string): boolean {
  try {
    const parsed = new URL(rawUrl);
    return parsed.protocol === 'https:'
      && parsed.hostname === 'wa.me'
      && parsed.username === ''
      && parsed.password === ''
      && parsed.port === ''
      && /^\/(?:\d+)?$/.test(parsed.pathname);
  } catch {
    return false;
  }
}

/** Checks the narrow sms: URL shape generated by the receipt-share flow. */
export function isSafeSmsShareUrl(rawUrl: string): boolean {
  try {
    const parsed = new URL(rawUrl);
    if (parsed.protocol !== 'sms:' || parsed.username || parsed.password || parsed.hash) return false;
    if (!/^\+?[1-9]\d{5,14}$/.test(parsed.pathname)) return false;
    return [...parsed.searchParams.keys()].every((key) => key === 'body') && parsed.searchParams.has('body');
  } catch {
    return false;
  }
}
